CREATE TABLE USER (
    ID INTEGER,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PROFILE_ID INTEGER,
    PRIMARY KEY ID,
    FOREIGN KEY (PROFILE_ID) REFERENCES USER_PROFILES(ID)
);

CREATE TABLE USER_PROFILES(
    ID INTEGER,
    UNIT VARCHAR(25) NOT NULL,
    TEAM  VARCHAR(25) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ID
);
